# Generated by Django 4.2.4 on 2023-09-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
                ('joined_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=100)),
                ('shop_domain', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=50)),
            ],
        ),
    ]
