# Generated by Django 4.2.4 on 2023-09-06 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_shop_address_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_pin',
            field=models.IntegerField(default=777777),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='joined_in',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='address_pin',
            field=models.IntegerField(),
        ),
    ]
