# Generated by Django 4.2.4 on 2023-09-13 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customer_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shop'),
        ),
    ]
