# Generated by Django 4.2.4 on 2023-09-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop_id',
        ),
    ]
