# Generated by Django 4.2.4 on 2023-09-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customer_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
