# Generated by Django 4.2.4 on 2023-09-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customer_customer_id_alter_shop_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop_id',
        ),
    ]
