# Generated by Django 4.2.4 on 2023-09-13 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_customer_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.shop'),
            preserve_default=False,
        ),
    ]
