# Generated by Django 4.2.4 on 2023-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_customer_shop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_pin',
            field=models.IntegerField(null=True),
        ),
    ]
