# Generated by Django 4.2.4 on 2023-09-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customer_address_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='shop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.shop'),
        ),
    ]
