# Generated by Django 4.2.4 on 2023-09-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_customer_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='shop_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='shop_id',
            field=models.ManyToManyField(blank=True, related_name='customers', to='users.shop'),
        ),
    ]
