# Generated by Django 4.2.4 on 2023-09-29 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_customer_shop_id_customer_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shop_id',
            new_name='shops',
        ),
    ]
