# Generated by Django 4.2.4 on 2023-09-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_shop_id_customer_shops'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='shops',
            new_name='shop_id',
        ),
    ]
