# Generated by Django 4.2.4 on 2023-09-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_order_order_id_alter_orderdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_mode',
            field=models.BooleanField(help_text='0-offline 1-online'),
        ),
    ]
