# Generated by Django 4.2.4 on 2023-09-23 09:45

from django.db import migrations, models
import seller.models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_order_order_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=0, help_text='0-pending, 1-completed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to=seller.models.getFileName),
        ),
    ]
